/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Valid values: * APTD - Appointment required at delivery * APTP - Appointment required at pickup * COD - Collect on delivery * EXPD - Expedited Service * GTD_AM- Guaranteed service - by Morning * GTD_NOON- Guaranteed service - by Noon   * GTD_PM- Guaranteed service - by End of Day * HAZ - Hazardous material * IDL - Inside delivery * INBD - In bond shipment * INS - Excess Liability * IPU - Inside pickup * LFTD - Lift gate required at delivery * LFTP - Lift gate required at pickup * LTDAD - Limited access delivery * LTDAP - Limited access pickup * MARK - Marked or tagged * MNC - Must notify consignee * OVR - Over dimension/excessive length * PPD - Perishables (food) * PSC - Protective from cold * PSH - Protective from heat * PSN - Poisonous material * REP - Residential pickup * RES - Residential delivery * SRT - Sort and segregate * SS - Single Shipment * TCS - Time Crititcal Service 
 */
@Schema(description = "Valid values: * APTD - Appointment required at delivery * APTP - Appointment required at pickup * COD - Collect on delivery * EXPD - Expedited Service * GTD_AM- Guaranteed service - by Morning * GTD_NOON- Guaranteed service - by Noon   * GTD_PM- Guaranteed service - by End of Day * HAZ - Hazardous material * IDL - Inside delivery * INBD - In bond shipment * INS - Excess Liability * IPU - Inside pickup * LFTD - Lift gate required at delivery * LFTP - Lift gate required at pickup * LTDAD - Limited access delivery * LTDAP - Limited access pickup * MARK - Marked or tagged * MNC - Must notify consignee * OVR - Over dimension/excessive length * PPD - Perishables (food) * PSC - Protective from cold * PSH - Protective from heat * PSN - Poisonous material * REP - Residential pickup * RES - Residential delivery * SRT - Sort and segregate * SS - Single Shipment * TCS - Time Crititcal Service ")
public class AccessorialCodes {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessorialCodes {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
