/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Required when accessorial code SRT is present in the accessorial.codes list.  
 */
@Schema(description = "Required when accessorial code SRT is present in the accessorial.codes list.  ")

public class BOLRequestAccessorialsSortAndSegregateDetails {
  @SerializedName("pieces")
  private Integer pieces = null;

  public BOLRequestAccessorialsSortAndSegregateDetails pieces(Integer pieces) {
    this.pieces = pieces;
    return this;
  }

   /**
   * Number of pieces in a shipment to be sorted/segregated
   * @return pieces
  **/
  @Schema(example = "25", description = "Number of pieces in a shipment to be sorted/segregated")
  public Integer getPieces() {
    return pieces;
  }

  public void setPieces(Integer pieces) {
    this.pieces = pieces;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsSortAndSegregateDetails boLRequestAccessorialsSortAndSegregateDetails = (BOLRequestAccessorialsSortAndSegregateDetails) o;
    return Objects.equals(this.pieces, boLRequestAccessorialsSortAndSegregateDetails.pieces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pieces);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsSortAndSegregateDetails {\n");
    
    sb.append("    pieces: ").append(toIndentedString(pieces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
