/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestReferenceNumbersPo
 */


public class BOLRequestReferenceNumbersPo {
  @SerializedName("number")
  private String number = null;

  @SerializedName("pieces")
  private Integer pieces = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("palletized")
  private Boolean palletized = null;

  @SerializedName("additionalShipperInfo")
  private String additionalShipperInfo = null;

  public BOLRequestReferenceNumbersPo number(String number) {
    this.number = number;
    return this;
  }

   /**
   * The Purchase Order number.
   * @return number
  **/
  @Schema(example = "554238", description = "The Purchase Order number.")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public BOLRequestReferenceNumbersPo pieces(Integer pieces) {
    this.pieces = pieces;
    return this;
  }

   /**
   * Total pieces associated with the Purchase Order
   * @return pieces
  **/
  @Schema(example = "5", description = "Total pieces associated with the Purchase Order")
  public Integer getPieces() {
    return pieces;
  }

  public void setPieces(Integer pieces) {
    this.pieces = pieces;
  }

  public BOLRequestReferenceNumbersPo weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Total weight associated with the Purchase Order
   * @return weight
  **/
  @Schema(example = "150", description = "Total weight associated with the Purchase Order")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public BOLRequestReferenceNumbersPo palletized(Boolean palletized) {
    this.palletized = palletized;
    return this;
  }

   /**
   * Indicates whether or not the pieces associated with the purchase order are on a pallet/slip/skid or not.
   * @return palletized
  **/
  @Schema(example = "true", description = "Indicates whether or not the pieces associated with the purchase order are on a pallet/slip/skid or not.")
  public Boolean isPalletized() {
    return palletized;
  }

  public void setPalletized(Boolean palletized) {
    this.palletized = palletized;
  }

  public BOLRequestReferenceNumbersPo additionalShipperInfo(String additionalShipperInfo) {
    this.additionalShipperInfo = additionalShipperInfo;
    return this;
  }

   /**
   * Additional information from shipper per line item
   * @return additionalShipperInfo
  **/
  @Schema(example = "Freight must always stay upright", description = "Additional information from shipper per line item")
  public String getAdditionalShipperInfo() {
    return additionalShipperInfo;
  }

  public void setAdditionalShipperInfo(String additionalShipperInfo) {
    this.additionalShipperInfo = additionalShipperInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestReferenceNumbersPo boLRequestReferenceNumbersPo = (BOLRequestReferenceNumbersPo) o;
    return Objects.equals(this.number, boLRequestReferenceNumbersPo.number) &&
        Objects.equals(this.pieces, boLRequestReferenceNumbersPo.pieces) &&
        Objects.equals(this.weight, boLRequestReferenceNumbersPo.weight) &&
        Objects.equals(this.palletized, boLRequestReferenceNumbersPo.palletized) &&
        Objects.equals(this.additionalShipperInfo, boLRequestReferenceNumbersPo.additionalShipperInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, pieces, weight, palletized, additionalShipperInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestReferenceNumbersPo {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    pieces: ").append(toIndentedString(pieces)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    palletized: ").append(toIndentedString(palletized)).append("\n");
    sb.append("    additionalShipperInfo: ").append(toIndentedString(additionalShipperInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
