/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Required when accessorial code COD is present in the accessorial.codes list.  
 */
@Schema(description = "Required when accessorial code COD is present in the accessorial.codes list.  ")
public class BOLRequestAccessorialsCodRemitTo {
  @SerializedName("name")
  private String name = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateProvince")
  private String stateProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("country")
  private String country = null;

  public BOLRequestAccessorialsCodRemitTo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the remit to company.
   * @return name
  **/
  @Schema(example = "Dog Beds by Stella", description = "Name of the remit to company.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BOLRequestAccessorialsCodRemitTo address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Primary Address line of the remit to company.
   * @return address1
  **/
  @Schema(example = "121 S. Cliffwood Ave.", description = "Primary Address line of the remit to company.")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public BOLRequestAccessorialsCodRemitTo address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Secondary Address of the remit to company.
   * @return address2
  **/
  @Schema(example = "Suite 55", description = "Secondary Address of the remit to company.")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public BOLRequestAccessorialsCodRemitTo city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City Name of the remit to company.
   * @return city
  **/
  @Schema(example = "Los Angeles", description = "City Name of the remit to company.")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BOLRequestAccessorialsCodRemitTo stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * Two letter state/province code of the remit to company.  Valid Values: See the State_Province_Codes schema at the bottom of this page. 
   * @return stateProvince
  **/
  @Schema(example = "CA", description = "Two letter state/province code of the remit to company.  Valid Values: See the State_Province_Codes schema at the bottom of this page. ")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }

  public BOLRequestAccessorialsCodRemitTo postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The 5-digit (or 6-characters for Canada) zip code of the remit to company.  Valid formats: * 12345 (5 digits - USA/MEX) * A1A1A1 (6 characters - CAN) * A1A1A (5 characters - CAN) 
   * @return postalCode
  **/
  @Schema(example = "90001", description = "The 5-digit (or 6-characters for Canada) zip code of the remit to company.  Valid formats: * 12345 (5 digits - USA/MEX) * A1A1A1 (6 characters - CAN) * A1A1A (5 characters - CAN) ")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public BOLRequestAccessorialsCodRemitTo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Three letter country code of the remit to company.  Valid Values: See the Country_Codes schema at the bottom of this page. 
   * @return country
  **/
  @Schema(example = "USA", description = "Three letter country code of the remit to company.  Valid Values: See the Country_Codes schema at the bottom of this page. ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsCodRemitTo boLRequestAccessorialsCodRemitTo = (BOLRequestAccessorialsCodRemitTo) o;
    return Objects.equals(this.name, boLRequestAccessorialsCodRemitTo.name) &&
        Objects.equals(this.address1, boLRequestAccessorialsCodRemitTo.address1) &&
        Objects.equals(this.address2, boLRequestAccessorialsCodRemitTo.address2) &&
        Objects.equals(this.city, boLRequestAccessorialsCodRemitTo.city) &&
        Objects.equals(this.stateProvince, boLRequestAccessorialsCodRemitTo.stateProvince) &&
        Objects.equals(this.postalCode, boLRequestAccessorialsCodRemitTo.postalCode) &&
        Objects.equals(this.country, boLRequestAccessorialsCodRemitTo.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address1, address2, city, stateProvince, postalCode, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsCodRemitTo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
