/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestCustomsBrokerContact;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestCustomsBroker
 */


public class BOLRequestCustomsBroker {
  @SerializedName("name")
  private String name = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateProvince")
  private String stateProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("contact")
  private BOLRequestCustomsBrokerContact contact = null;

  public BOLRequestCustomsBroker name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Company name associated with the customsBroker location.
   * @return name
  **/
  @Schema(example = "Closets Closets Closets", description = "Company name associated with the customsBroker location.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BOLRequestCustomsBroker address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Primary Address line for the customsBroker location
   * @return address1
  **/
  @Schema(example = "12 S. Closets Place", description = "Primary Address line for the customsBroker location")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public BOLRequestCustomsBroker address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Secondary Address line for the customsBroker location
   * @return address2
  **/
  @Schema(example = "ste 3", description = "Secondary Address line for the customsBroker location")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public BOLRequestCustomsBroker city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City Name for the customsBroker location
   * @return city
  **/
  @Schema(example = "Los Angeles", description = "City Name for the customsBroker location")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BOLRequestCustomsBroker stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * Two letter state/province code for the customsBroker location.  Valid Values: See the State_Province_Codes schema at the bottom of this page. 
   * @return stateProvince
  **/
  @Schema(example = "CA", description = "Two letter state/province code for the customsBroker location.  Valid Values: See the State_Province_Codes schema at the bottom of this page. ")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }

  public BOLRequestCustomsBroker postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The 5-digit (or 6-characters for Canada) zip code ofor the customsBroker location.  Valid formats:   * 12345 (5 digits - USA/MEX)   * A1A1A1 (6 characters - CAN)   * A1A1A (5 characters - CAN) 
   * @return postalCode
  **/
  @Schema(example = "90001", description = "The 5-digit (or 6-characters for Canada) zip code ofor the customsBroker location.  Valid formats:   * 12345 (5 digits - USA/MEX)   * A1A1A1 (6 characters - CAN)   * A1A1A (5 characters - CAN) ")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public BOLRequestCustomsBroker country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Three letter country code for the customsBroker location.  Valid Values: See the Country_Codes schema at the bottom of this page. 
   * @return country
  **/
  @Schema(example = "USA", description = "Three letter country code for the customsBroker location.  Valid Values: See the Country_Codes schema at the bottom of this page. ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BOLRequestCustomsBroker contact(BOLRequestCustomsBrokerContact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @Schema(description = "")
  public BOLRequestCustomsBrokerContact getContact() {
    return contact;
  }

  public void setContact(BOLRequestCustomsBrokerContact contact) {
    this.contact = contact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestCustomsBroker boLRequestCustomsBroker = (BOLRequestCustomsBroker) o;
    return Objects.equals(this.name, boLRequestCustomsBroker.name) &&
        Objects.equals(this.address1, boLRequestCustomsBroker.address1) &&
        Objects.equals(this.address2, boLRequestCustomsBroker.address2) &&
        Objects.equals(this.city, boLRequestCustomsBroker.city) &&
        Objects.equals(this.stateProvince, boLRequestCustomsBroker.stateProvince) &&
        Objects.equals(this.postalCode, boLRequestCustomsBroker.postalCode) &&
        Objects.equals(this.country, boLRequestCustomsBroker.country) &&
        Objects.equals(this.contact, boLRequestCustomsBroker.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address1, address2, city, stateProvince, postalCode, country, contact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestCustomsBroker {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
