/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLResponseImages
 */


public class BOLResponseImages {
  @SerializedName("bol")
  private String bol = null;

  @SerializedName("shippingLabels")
  private String shippingLabels = null;

  public BOLResponseImages bol(String bol) {
    this.bol = bol;
    return this;
  }

   /**
   * Base 64 encoded PDF of the populated Bill Of Lading
   * @return bol
  **/
  @Schema(example = "JVBERi0xLjcKCjQgMCBvYmoKPDwKL0JpdHNQZXJDb21wb25lbnQgOAovQ29sb3JTcGFjZSAvRGV2a......", description = "Base 64 encoded PDF of the populated Bill Of Lading")
  public String getBol() {
    return bol;
  }

  public void setBol(String bol) {
    this.bol = bol;
  }

  public BOLResponseImages shippingLabels(String shippingLabels) {
    this.shippingLabels = shippingLabels;
    return this;
  }

   /**
   * Base 64 encoded PDF of the populated shipping labels
   * @return shippingLabels
  **/
  @Schema(example = "JVBERi0xLjcKCjQgMCBvYmoKPDwKL0JpdHNQZXJDb21wb25lbnQgOAovQ29sb3JTcGFjZSAvRGV2a......", description = "Base 64 encoded PDF of the populated shipping labels")
  public String getShippingLabels() {
    return shippingLabels;
  }

  public void setShippingLabels(String shippingLabels) {
    this.shippingLabels = shippingLabels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLResponseImages boLResponseImages = (BOLResponseImages) o;
    return Objects.equals(this.bol, boLResponseImages.bol) &&
        Objects.equals(this.shippingLabels, boLResponseImages.shippingLabels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bol, shippingLabels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLResponseImages {\n");
    
    sb.append("    bol: ").append(toIndentedString(bol)).append("\n");
    sb.append("    shippingLabels: ").append(toIndentedString(shippingLabels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
