/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestShipmentTotals
 */


public class BOLRequestShipmentTotals {
  @SerializedName("grossWeight")
  private Integer grossWeight = null;

  @SerializedName("netWeight")
  private Integer netWeight = null;

  @SerializedName("handlingUnits")
  private Integer handlingUnits = null;

  @SerializedName("linearLength")
  private Integer linearLength = null;

  @SerializedName("cubicFeet")
  private Integer cubicFeet = null;

  public BOLRequestShipmentTotals grossWeight(Integer grossWeight) {
    this.grossWeight = grossWeight;
    return this;
  }

   /**
   * Gross weight (in pounds) of the entire shipment.
   * @return grossWeight
  **/
  @Schema(example = "2000", description = "Gross weight (in pounds) of the entire shipment.")
  public Integer getGrossWeight() {
    return grossWeight;
  }

  public void setGrossWeight(Integer grossWeight) {
    this.grossWeight = grossWeight;
  }

  public BOLRequestShipmentTotals netWeight(Integer netWeight) {
    this.netWeight = netWeight;
    return this;
  }

   /**
   * Net weight (in pounds) of the entire shipment.
   * @return netWeight
  **/
  @Schema(example = "1993", description = "Net weight (in pounds) of the entire shipment.")
  public Integer getNetWeight() {
    return netWeight;
  }

  public void setNetWeight(Integer netWeight) {
    this.netWeight = netWeight;
  }

  public BOLRequestShipmentTotals handlingUnits(Integer handlingUnits) {
    this.handlingUnits = handlingUnits;
    return this;
  }

   /**
   * Handling unit count for the entire shipment
   * @return handlingUnits
  **/
  @Schema(example = "2", description = "Handling unit count for the entire shipment")
  public Integer getHandlingUnits() {
    return handlingUnits;
  }

  public void setHandlingUnits(Integer handlingUnits) {
    this.handlingUnits = handlingUnits;
  }

  public BOLRequestShipmentTotals linearLength(Integer linearLength) {
    this.linearLength = linearLength;
    return this;
  }

   /**
   * Linear length (in inches) for the entire shipment
   * @return linearLength
  **/
  @Schema(example = "96", description = "Linear length (in inches) for the entire shipment")
  public Integer getLinearLength() {
    return linearLength;
  }

  public void setLinearLength(Integer linearLength) {
    this.linearLength = linearLength;
  }

  public BOLRequestShipmentTotals cubicFeet(Integer cubicFeet) {
    this.cubicFeet = cubicFeet;
    return this;
  }

   /**
   * Cubic feet of the entire shipment.
   * @return cubicFeet
  **/
  @Schema(example = "7", description = "Cubic feet of the entire shipment.")
  public Integer getCubicFeet() {
    return cubicFeet;
  }

  public void setCubicFeet(Integer cubicFeet) {
    this.cubicFeet = cubicFeet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestShipmentTotals boLRequestShipmentTotals = (BOLRequestShipmentTotals) o;
    return Objects.equals(this.grossWeight, boLRequestShipmentTotals.grossWeight) &&
        Objects.equals(this.netWeight, boLRequestShipmentTotals.netWeight) &&
        Objects.equals(this.handlingUnits, boLRequestShipmentTotals.handlingUnits) &&
        Objects.equals(this.linearLength, boLRequestShipmentTotals.linearLength) &&
        Objects.equals(this.cubicFeet, boLRequestShipmentTotals.cubicFeet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grossWeight, netWeight, handlingUnits, linearLength, cubicFeet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestShipmentTotals {\n");
    
    sb.append("    grossWeight: ").append(toIndentedString(grossWeight)).append("\n");
    sb.append("    netWeight: ").append(toIndentedString(netWeight)).append("\n");
    sb.append("    handlingUnits: ").append(toIndentedString(handlingUnits)).append("\n");
    sb.append("    linearLength: ").append(toIndentedString(linearLength)).append("\n");
    sb.append("    cubicFeet: ").append(toIndentedString(cubicFeet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
