/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestCommoditiesHazardousDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestCommoditiesLineItems
 */


public class BOLRequestCommoditiesLineItems {
  @SerializedName("handlingUnitId")
  private String handlingUnitId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("pieces")
  private Integer pieces = null;

  @SerializedName("packagingType")
  private String packagingType = null;

  @SerializedName("classification")
  private String classification = null;

  @SerializedName("nmfc")
  private String nmfc = null;

  @SerializedName("nmfcSub")
  private String nmfcSub = null;

  @SerializedName("hazardous")
  private Boolean hazardous = null;

  @SerializedName("hazardousDetails")
  private BOLRequestCommoditiesHazardousDetails hazardousDetails = null;

  public BOLRequestCommoditiesLineItems handlingUnitId(String handlingUnitId) {
    this.handlingUnitId = handlingUnitId;
    return this;
  }

   /**
   * Unique identifier for the user to associate handling units with line items.
   * @return handlingUnitId
  **/
  @Schema(example = "unit1", description = "Unique identifier for the user to associate handling units with line items.")
  public String getHandlingUnitId() {
    return handlingUnitId;
  }

  public void setHandlingUnitId(String handlingUnitId) {
    this.handlingUnitId = handlingUnitId;
  }

  public BOLRequestCommoditiesLineItems description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the freight being described.
   * @return description
  **/
  @Schema(example = "Small frameless mirrors", required = true, description = "Description of the freight being described.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BOLRequestCommoditiesLineItems weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Total weight (in pounds) for the specified lineItem.
   * @return weight
  **/
  @Schema(example = "1500", required = true, description = "Total weight (in pounds) for the specified lineItem.")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public BOLRequestCommoditiesLineItems pieces(Integer pieces) {
    this.pieces = pieces;
    return this;
  }

   /**
   * Number of individual pieces for the line item being described.
   * @return pieces
  **/
  @Schema(example = "3", required = true, description = "Number of individual pieces for the line item being described.")
  public Integer getPieces() {
    return pieces;
  }

  public void setPieces(Integer pieces) {
    this.pieces = pieces;
  }

  public BOLRequestCommoditiesLineItems packagingType(String packagingType) {
    this.packagingType = packagingType;
    return this;
  }

   /**
   * Packaging type for the individual pieces of the line item being described.  Valid Values: See the Packaging_Types schema at the bottom of this page 
   * @return packagingType
  **/
  @Schema(example = "BOX", required = true, description = "Packaging type for the individual pieces of the line item being described.  Valid Values: See the Packaging_Types schema at the bottom of this page ")
  public String getPackagingType() {
    return packagingType;
  }

  public void setPackagingType(String packagingType) {
    this.packagingType = packagingType;
  }

  public BOLRequestCommoditiesLineItems classification(String classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Classification of the line item beind described.  Valid Values: See the Classification_Codes schema at the bottom of this page. 
   * @return classification
  **/
  @Schema(example = "55", required = true, description = "Classification of the line item beind described.  Valid Values: See the Classification_Codes schema at the bottom of this page. ")
  public String getClassification() {
    return classification;
  }

  public void setClassification(String classification) {
    this.classification = classification;
  }

  public BOLRequestCommoditiesLineItems nmfc(String nmfc) {
    this.nmfc = nmfc;
    return this;
  }

   /**
   * NMFC code of the freight being described.
   * @return nmfc
  **/
  @Schema(example = "86900", description = "NMFC code of the freight being described.")
  public String getNmfc() {
    return nmfc;
  }

  public void setNmfc(String nmfc) {
    this.nmfc = nmfc;
  }

  public BOLRequestCommoditiesLineItems nmfcSub(String nmfcSub) {
    this.nmfcSub = nmfcSub;
    return this;
  }

   /**
   * The Sub value for the NMFC of the freight being described.
   * @return nmfcSub
  **/
  @Schema(example = "3", description = "The Sub value for the NMFC of the freight being described.")
  public String getNmfcSub() {
    return nmfcSub;
  }

  public void setNmfcSub(String nmfcSub) {
    this.nmfcSub = nmfcSub;
  }

  public BOLRequestCommoditiesLineItems hazardous(Boolean hazardous) {
    this.hazardous = hazardous;
    return this;
  }

   /**
   * Identifies whether or not the freight being described ciontains hazardous materials.
   * @return hazardous
  **/
  @Schema(example = "true", required = true, description = "Identifies whether or not the freight being described ciontains hazardous materials.")
  public Boolean isHazardous() {
    return hazardous;
  }

  public void setHazardous(Boolean hazardous) {
    this.hazardous = hazardous;
  }

  public BOLRequestCommoditiesLineItems hazardousDetails(BOLRequestCommoditiesHazardousDetails hazardousDetails) {
    this.hazardousDetails = hazardousDetails;
    return this;
  }

   /**
   * Get hazardousDetails
   * @return hazardousDetails
  **/
  @Schema(description = "")
  public BOLRequestCommoditiesHazardousDetails getHazardousDetails() {
    return hazardousDetails;
  }

  public void setHazardousDetails(BOLRequestCommoditiesHazardousDetails hazardousDetails) {
    this.hazardousDetails = hazardousDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestCommoditiesLineItems boLRequestCommoditiesLineItems = (BOLRequestCommoditiesLineItems) o;
    return Objects.equals(this.handlingUnitId, boLRequestCommoditiesLineItems.handlingUnitId) &&
        Objects.equals(this.description, boLRequestCommoditiesLineItems.description) &&
        Objects.equals(this.weight, boLRequestCommoditiesLineItems.weight) &&
        Objects.equals(this.pieces, boLRequestCommoditiesLineItems.pieces) &&
        Objects.equals(this.packagingType, boLRequestCommoditiesLineItems.packagingType) &&
        Objects.equals(this.classification, boLRequestCommoditiesLineItems.classification) &&
        Objects.equals(this.nmfc, boLRequestCommoditiesLineItems.nmfc) &&
        Objects.equals(this.nmfcSub, boLRequestCommoditiesLineItems.nmfcSub) &&
        Objects.equals(this.hazardous, boLRequestCommoditiesLineItems.hazardous) &&
        Objects.equals(this.hazardousDetails, boLRequestCommoditiesLineItems.hazardousDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(handlingUnitId, description, weight, pieces, packagingType, classification, nmfc, nmfcSub, hazardous, hazardousDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestCommoditiesLineItems {\n");
    
    sb.append("    handlingUnitId: ").append(toIndentedString(handlingUnitId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    pieces: ").append(toIndentedString(pieces)).append("\n");
    sb.append("    packagingType: ").append(toIndentedString(packagingType)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    nmfc: ").append(toIndentedString(nmfc)).append("\n");
    sb.append("    nmfcSub: ").append(toIndentedString(nmfcSub)).append("\n");
    sb.append("    hazardous: ").append(toIndentedString(hazardous)).append("\n");
    sb.append("    hazardousDetails: ").append(toIndentedString(hazardousDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
