/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestAccessorialsAppointmentDetailsDelivery
 */

public class BOLRequestAccessorialsAppointmentDetailsDelivery {
  @SerializedName("start")
  private String start = null;

  @SerializedName("end")
  private String end = null;

  public BOLRequestAccessorialsAppointmentDetailsDelivery start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Starting appointment date (with or without time) the shipment is requested to be delivered.  Required when accessorials.code list include APTD.  Valid Formats: * YYYY-MM-DDTHH:mm:ss.sss (ISO 8601) 
   * @return start
  **/
  @Schema(example = "2021-05-20T00:00:00.000", description = "Starting appointment date (with or without time) the shipment is requested to be delivered.  Required when accessorials.code list include APTD.  Valid Formats: * YYYY-MM-DDTHH:mm:ss.sss (ISO 8601) ")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public BOLRequestAccessorialsAppointmentDetailsDelivery end(String end) {
    this.end = end;
    return this;
  }

   /**
   * Ending appointment date (with or without time) the shipment is requested to be delivered.  Valid Formats: * YYYY-MM-DDTHH:mm:ss.sss (ISO 8601) 
   * @return end
  **/
  @Schema(example = "2021-05-22T00:00:00.000", description = "Ending appointment date (with or without time) the shipment is requested to be delivered.  Valid Formats: * YYYY-MM-DDTHH:mm:ss.sss (ISO 8601) ")
  public String getEnd() {
    return end;
  }

  public void setEnd(String end) {
    this.end = end;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsAppointmentDetailsDelivery boLRequestAccessorialsAppointmentDetailsDelivery = (BOLRequestAccessorialsAppointmentDetailsDelivery) o;
    return Objects.equals(this.start, boLRequestAccessorialsAppointmentDetailsDelivery.start) &&
        Objects.equals(this.end, boLRequestAccessorialsAppointmentDetailsDelivery.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsAppointmentDetailsDelivery {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
