/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLResponseMessageStatusInformation;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Object containing message status details.
 */
@Schema(description = "Object containing message status details.")

public class BOLResponseMessageStatus {
  @SerializedName("status")
  private String status = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("resolution")
  private String resolution = null;

  @SerializedName("information")
  private List<BOLResponseMessageStatusInformation> information = null;

  public BOLResponseMessageStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Indicates the status of the request. &lt;br&gt;&lt;br&gt; PASS - Request is successful with no exceptions.&lt;br&gt; FAIL - Request is unsuccessful due to some exception.&lt;br&gt; WARNING - Request is successful with some exception. 
   * @return status
  **/
  @Schema(example = "PASS", description = "Indicates the status of the request. <br><br> PASS - Request is successful with no exceptions.<br> FAIL - Request is unsuccessful due to some exception.<br> WARNING - Request is successful with some exception. ")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public BOLResponseMessageStatus code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Indicates response detail code.
   * @return code
  **/
  @Schema(example = "10000000", description = "Indicates response detail code.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BOLResponseMessageStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Provides information pertaining to the response code.
   * @return message
  **/
  @Schema(example = "Transaction was successful.", description = "Provides information pertaining to the response code.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BOLResponseMessageStatus resolution(String resolution) {
    this.resolution = resolution;
    return this;
  }

   /**
   * Provides guidance pertaining to the response code.
   * @return resolution
  **/
  @Schema(description = "Provides guidance pertaining to the response code.")
  public String getResolution() {
    return resolution;
  }

  public void setResolution(String resolution) {
    this.resolution = resolution;
  }

  public BOLResponseMessageStatus information(List<BOLResponseMessageStatusInformation> information) {
    this.information = information;
    return this;
  }

  public BOLResponseMessageStatus addInformationItem(BOLResponseMessageStatusInformation informationItem) {
    if (this.information == null) {
      this.information = new ArrayList<BOLResponseMessageStatusInformation>();
    }
    this.information.add(informationItem);
    return this;
  }

   /**
   * Get information
   * @return information
  **/
  @Schema(example = "[]", description = "")
  public List<BOLResponseMessageStatusInformation> getInformation() {
    return information;
  }

  public void setInformation(List<BOLResponseMessageStatusInformation> information) {
    this.information = information;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLResponseMessageStatus boLResponseMessageStatus = (BOLResponseMessageStatus) o;
    return Objects.equals(this.status, boLResponseMessageStatus.status) &&
        Objects.equals(this.code, boLResponseMessageStatus.code) &&
        Objects.equals(this.message, boLResponseMessageStatus.message) &&
        Objects.equals(this.resolution, boLResponseMessageStatus.resolution) &&
        Objects.equals(this.information, boLResponseMessageStatus.information);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, code, message, resolution, information);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLResponseMessageStatus {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    information: ").append(toIndentedString(information)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
