/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestCommoditiesHandlingUnits;
import com.nmfta.ebol.model.BOLRequestCommoditiesLineItems;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BOLRequestCommodities
 */


public class BOLRequestCommodities {
  @SerializedName("handlingUnits")
  private List<BOLRequestCommoditiesHandlingUnits> handlingUnits = new ArrayList<BOLRequestCommoditiesHandlingUnits>();

  @SerializedName("lineItems")
  private List<BOLRequestCommoditiesLineItems> lineItems = new ArrayList<BOLRequestCommoditiesLineItems>();

  public BOLRequestCommodities handlingUnits(List<BOLRequestCommoditiesHandlingUnits> handlingUnits) {
    this.handlingUnits = handlingUnits;
    return this;
  }

  public BOLRequestCommodities addHandlingUnitsItem(BOLRequestCommoditiesHandlingUnits handlingUnitsItem) {
    this.handlingUnits.add(handlingUnitsItem);
    return this;
  }

   /**
   * Get handlingUnits
   * @return handlingUnits
  **/
  @Schema(required = true, description = "")
  public List<BOLRequestCommoditiesHandlingUnits> getHandlingUnits() {
    return handlingUnits;
  }

  public void setHandlingUnits(List<BOLRequestCommoditiesHandlingUnits> handlingUnits) {
    this.handlingUnits = handlingUnits;
  }

  public BOLRequestCommodities lineItems(List<BOLRequestCommoditiesLineItems> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public BOLRequestCommodities addLineItemsItem(BOLRequestCommoditiesLineItems lineItemsItem) {
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * Get lineItems
   * @return lineItems
  **/
  @Schema(required = true, description = "")
  public List<BOLRequestCommoditiesLineItems> getLineItems() {
    return lineItems;
  }

  public void setLineItems(List<BOLRequestCommoditiesLineItems> lineItems) {
    this.lineItems = lineItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestCommodities boLRequestCommodities = (BOLRequestCommodities) o;
    return Objects.equals(this.handlingUnits, boLRequestCommodities.handlingUnits) &&
        Objects.equals(this.lineItems, boLRequestCommodities.lineItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(handlingUnits, lineItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestCommodities {\n");
    
    sb.append("    handlingUnits: ").append(toIndentedString(handlingUnits)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
