/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import org.hibernate.annotations.Type;

/**
 * Objects and/or attributes that are required are indicated by a _**red asterisk**_*. For those that are conditionally required, it will be indicated within their description, including the condition in which they are required.
 */
@Schema(description = "Objects and/or attributes that are required are indicated by a _**red asterisk**_*. For those that are conditionally required, it will be indicated within their description, including the condition in which they are required.")
@Entity
public class BOLRequest {
	
  @Id
  @GeneratedValue
  private Long id;

  @SerializedName("bol")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestBol bol = null;

  @SerializedName("images")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestImages images = null;

  @SerializedName("referenceNumbers")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestReferenceNumbers referenceNumbers = null;

  @SerializedName("payment")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestPayment payment = null;

  @SerializedName("commodities")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestCommodities commodities = null;

  @SerializedName("shipmentTotals")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestShipmentTotals shipmentTotals = null;

  @SerializedName("accessorials")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestAccessorials accessorials = null;

  @SerializedName("origin")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestOrigin origin = null;

  @SerializedName("destination")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestDestination destination = null;

  @SerializedName("billTo")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestBillTo billTo = null;

  @SerializedName("customsBroker")
  @Column(columnDefinition="json")
  @Type(JsonType.class)
  private BOLRequestCustomsBroker customsBroker = null;

  public BOLRequest bol(BOLRequestBol bol) {
    this.bol = bol;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  public Long getId() {
	  return id;
  }
  
  public void setId(Long id)
  {
	  this.id = id;
  }
  
   /**
   * Get bol
   * @return bol
  **/
  @Schema(required = true, description = "")
  public BOLRequestBol getBol() {
    return bol;
  }

  public void setBol(BOLRequestBol bol) {
    this.bol = bol;
  }

  public BOLRequest images(BOLRequestImages images) {
    this.images = images;
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public BOLRequestImages getImages() {
    return images;
  }

  public void setImages(BOLRequestImages images) {
    this.images = images;
  }

  public BOLRequest referenceNumbers(BOLRequestReferenceNumbers referenceNumbers) {
    this.referenceNumbers = referenceNumbers;
    return this;
  }

   /**
   * Get referenceNumbers
   * @return referenceNumbers
  **/
  @Schema(description = "")
  public BOLRequestReferenceNumbers getReferenceNumbers() {
    return referenceNumbers;
  }

  public void setReferenceNumbers(BOLRequestReferenceNumbers referenceNumbers) {
    this.referenceNumbers = referenceNumbers;
  }

  public BOLRequest payment(BOLRequestPayment payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @Schema(required = true, description = "")
  public BOLRequestPayment getPayment() {
    return payment;
  }

  public void setPayment(BOLRequestPayment payment) {
    this.payment = payment;
  }

  public BOLRequest commodities(BOLRequestCommodities commodities) {
    this.commodities = commodities;
    return this;
  }

   /**
   * Get commodities
   * @return commodities
  **/
  @Schema(required = true, description = "")
  public BOLRequestCommodities getCommodities() {
    return commodities;
  }

  public void setCommodities(BOLRequestCommodities commodities) {
    this.commodities = commodities;
  }

  public BOLRequest shipmentTotals(BOLRequestShipmentTotals shipmentTotals) {
    this.shipmentTotals = shipmentTotals;
    return this;
  }

   /**
   * Get shipmentTotals
   * @return shipmentTotals
  **/
  @Schema(description = "")
  public BOLRequestShipmentTotals getShipmentTotals() {
    return shipmentTotals;
  }

  public void setShipmentTotals(BOLRequestShipmentTotals shipmentTotals) {
    this.shipmentTotals = shipmentTotals;
  }

  public BOLRequest accessorials(BOLRequestAccessorials accessorials) {
    this.accessorials = accessorials;
    return this;
  }

   /**
   * Get accessorials
   * @return accessorials
  **/
  @Schema(description = "")
  public BOLRequestAccessorials getAccessorials() {
    return accessorials;
  }

  public void setAccessorials(BOLRequestAccessorials accessorials) {
    this.accessorials = accessorials;
  }

  public BOLRequest origin(BOLRequestOrigin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  @Schema(required = true, description = "")
  public BOLRequestOrigin getOrigin() {
    return origin;
  }

  public void setOrigin(BOLRequestOrigin origin) {
    this.origin = origin;
  }

  public BOLRequest destination(BOLRequestDestination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @Schema(required = true, description = "")
  public BOLRequestDestination getDestination() {
    return destination;
  }

  public void setDestination(BOLRequestDestination destination) {
    this.destination = destination;
  }

  public BOLRequest billTo(BOLRequestBillTo billTo) {
    this.billTo = billTo;
    return this;
  }

   /**
   * Get billTo
   * @return billTo
  **/
  @Schema(required = true, description = "")
  public BOLRequestBillTo getBillTo() {
    return billTo;
  }

  public void setBillTo(BOLRequestBillTo billTo) {
    this.billTo = billTo;
  }

  public BOLRequest customsBroker(BOLRequestCustomsBroker customsBroker) {
    this.customsBroker = customsBroker;
    return this;
  }

   /**
   * Get customsBroker
   * @return customsBroker
  **/
  @Schema(description = "")
  public BOLRequestCustomsBroker getCustomsBroker() {
    return customsBroker;
  }

  public void setCustomsBroker(BOLRequestCustomsBroker customsBroker) {
    this.customsBroker = customsBroker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequest boLRequest = (BOLRequest) o;
    return Objects.equals(this.bol, boLRequest.bol) &&
        Objects.equals(this.images, boLRequest.images) &&
        Objects.equals(this.referenceNumbers, boLRequest.referenceNumbers) &&
        Objects.equals(this.payment, boLRequest.payment) &&
        Objects.equals(this.commodities, boLRequest.commodities) &&
        Objects.equals(this.shipmentTotals, boLRequest.shipmentTotals) &&
        Objects.equals(this.accessorials, boLRequest.accessorials) &&
        Objects.equals(this.origin, boLRequest.origin) &&
        Objects.equals(this.destination, boLRequest.destination) &&
        Objects.equals(this.billTo, boLRequest.billTo) &&
        Objects.equals(this.customsBroker, boLRequest.customsBroker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bol, images, referenceNumbers, payment, commodities, shipmentTotals, accessorials, origin, destination, billTo, customsBroker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequest {\n");
    
    sb.append("    bol: ").append(toIndentedString(bol)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    referenceNumbers: ").append(toIndentedString(referenceNumbers)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    commodities: ").append(toIndentedString(commodities)).append("\n");
    sb.append("    shipmentTotals: ").append(toIndentedString(shipmentTotals)).append("\n");
    sb.append("    accessorials: ").append(toIndentedString(accessorials)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    billTo: ").append(toIndentedString(billTo)).append("\n");
    sb.append("    customsBroker: ").append(toIndentedString(customsBroker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
