/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestOriginContact;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestOrigin
 */


public class BOLRequestOrigin {
  @SerializedName("account")
  private String account = null;

  @SerializedName("locationId")
  private String locationId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateProvince")
  private String stateProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("contact")
  private BOLRequestOriginContact contact = null;

  public BOLRequestOrigin account(String account) {
    this.account = account;
    return this;
  }

   /**
   * Company&#x27;s account number/id for the origin.
   * @return account
  **/
  @Schema(example = "12345", description = "Company's account number/id for the origin.")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public BOLRequestOrigin locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Company&#x27;s location id for the origin
   * @return locationId
  **/
  @Schema(example = "808", description = "Company's location id for the origin")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public BOLRequestOrigin name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Company name associated with the origin location.
   * @return name
  **/
  @Schema(example = "Closets Closets Closets", required = true, description = "Company name associated with the origin location.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BOLRequestOrigin address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Primary Address line for the origin location
   * @return address1
  **/
  @Schema(example = "12 S. Closets Place", required = true, description = "Primary Address line for the origin location")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public BOLRequestOrigin address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Secondary Address line for the origin location
   * @return address2
  **/
  @Schema(example = "ste 3", description = "Secondary Address line for the origin location")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public BOLRequestOrigin city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City Name for the origin location
   * @return city
  **/
  @Schema(example = "Los Angeles", required = true, description = "City Name for the origin location")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BOLRequestOrigin stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * Two letter state/province code for the origin location.  Valid Values: See the State_Province_Codes schema at the bottom of this page. 
   * @return stateProvince
  **/
  @Schema(example = "CA", required = true, description = "Two letter state/province code for the origin location.  Valid Values: See the State_Province_Codes schema at the bottom of this page. ")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }

  public BOLRequestOrigin postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The 5-digit (or 6-characters for Canada) zip code ofor the origin location.  Valid formats:   * 12345 (5 digits - USA/MEX)   * A1A1A1 (6 characters - CAN)   * A1A1A (5 characters - CAN) 
   * @return postalCode
  **/
  @Schema(example = "90001", required = true, description = "The 5-digit (or 6-characters for Canada) zip code ofor the origin location.  Valid formats:   * 12345 (5 digits - USA/MEX)   * A1A1A1 (6 characters - CAN)   * A1A1A (5 characters - CAN) ")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public BOLRequestOrigin country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Three letter country code for the origin location.  Valid Values: See the Country_Codes schema at the bottom of this page. 
   * @return country
  **/
  @Schema(example = "USA", description = "Three letter country code for the origin location.  Valid Values: See the Country_Codes schema at the bottom of this page. ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BOLRequestOrigin contact(BOLRequestOriginContact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @Schema(required = true, description = "")
  public BOLRequestOriginContact getContact() {
    return contact;
  }

  public void setContact(BOLRequestOriginContact contact) {
    this.contact = contact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestOrigin boLRequestOrigin = (BOLRequestOrigin) o;
    return Objects.equals(this.account, boLRequestOrigin.account) &&
        Objects.equals(this.locationId, boLRequestOrigin.locationId) &&
        Objects.equals(this.name, boLRequestOrigin.name) &&
        Objects.equals(this.address1, boLRequestOrigin.address1) &&
        Objects.equals(this.address2, boLRequestOrigin.address2) &&
        Objects.equals(this.city, boLRequestOrigin.city) &&
        Objects.equals(this.stateProvince, boLRequestOrigin.stateProvince) &&
        Objects.equals(this.postalCode, boLRequestOrigin.postalCode) &&
        Objects.equals(this.country, boLRequestOrigin.country) &&
        Objects.equals(this.contact, boLRequestOrigin.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, locationId, name, address1, address2, city, stateProvince, postalCode, country, contact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestOrigin {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
