/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestReferenceNumbersAdditionalReferences;
import com.nmfta.ebol.model.BOLRequestReferenceNumbersPo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BOLRequestReferenceNumbers
 */


public class BOLRequestReferenceNumbers {
  @SerializedName("pro")
  private String pro = null;

  @SerializedName("estimate")
  private String estimate = null;

  @SerializedName("shipmentId")
  private String shipmentId = null;

  @SerializedName("masterBol")
  private String masterBol = null;

  @SerializedName("bol")
  private List<String> bol = null;

  @SerializedName("po")
  private List<BOLRequestReferenceNumbersPo> po = null;

  @SerializedName("additionalReferences")
  private List<BOLRequestReferenceNumbersAdditionalReferences> additionalReferences = null;

  public BOLRequestReferenceNumbers pro(String pro) {
    this.pro = pro;
    return this;
  }

   /**
   * Shipper&#x27;s pre-assigned PRO number for the requested carrier. If not provided, one will be auto assigned by the carrier.
   * @return pro
  **/
  @Schema(example = "123456-7", description = "Shipper's pre-assigned PRO number for the requested carrier. If not provided, one will be auto assigned by the carrier.")
  public String getPro() {
    return pro;
  }

  public void setPro(String pro) {
    this.pro = pro;
  }

  public BOLRequestReferenceNumbers estimate(String estimate) {
    this.estimate = estimate;
    return this;
  }

   /**
   * Estimate number provided by the carrier after submitting a rate estimate request.
   * @return estimate
  **/
  @Schema(example = "E556724", description = "Estimate number provided by the carrier after submitting a rate estimate request.")
  public String getEstimate() {
    return estimate;
  }

  public void setEstimate(String estimate) {
    this.estimate = estimate;
  }

  public BOLRequestReferenceNumbers shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Shipment Id (SID) number for the shipment.
   * @return shipmentId
  **/
  @Schema(example = "SID9743985", description = "Shipment Id (SID) number for the shipment.")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public BOLRequestReferenceNumbers masterBol(String masterBol) {
    this.masterBol = masterBol;
    return this;
  }

   /**
   * Master Bill of Lading number for the shipment.
   * @return masterBol
  **/
  @Schema(example = "MBL98472587", description = "Master Bill of Lading number for the shipment.")
  public String getMasterBol() {
    return masterBol;
  }

  public void setMasterBol(String masterBol) {
    this.masterBol = masterBol;
  }

  public BOLRequestReferenceNumbers bol(List<String> bol) {
    this.bol = bol;
    return this;
  }

  public BOLRequestReferenceNumbers addBolItem(String bolItem) {
    if (this.bol == null) {
      this.bol = new ArrayList<String>();
    }
    this.bol.add(bolItem);
    return this;
  }

   /**
   * Get bol
   * @return bol
  **/
  @Schema(example = "[\"BL19498432\",\"BL99744565\"]", description = "")
  public List<String> getBol() {
    return bol;
  }

  public void setBol(List<String> bol) {
    this.bol = bol;
  }

  public BOLRequestReferenceNumbers po(List<BOLRequestReferenceNumbersPo> po) {
    this.po = po;
    return this;
  }

  public BOLRequestReferenceNumbers addPoItem(BOLRequestReferenceNumbersPo poItem) {
    if (this.po == null) {
      this.po = new ArrayList<BOLRequestReferenceNumbersPo>();
    }
    this.po.add(poItem);
    return this;
  }

   /**
   * Get po
   * @return po
  **/
  @Schema(description = "")
  public List<BOLRequestReferenceNumbersPo> getPo() {
    return po;
  }

  public void setPo(List<BOLRequestReferenceNumbersPo> po) {
    this.po = po;
  }

  public BOLRequestReferenceNumbers additionalReferences(List<BOLRequestReferenceNumbersAdditionalReferences> additionalReferences) {
    this.additionalReferences = additionalReferences;
    return this;
  }

  public BOLRequestReferenceNumbers addAdditionalReferencesItem(BOLRequestReferenceNumbersAdditionalReferences additionalReferencesItem) {
    if (this.additionalReferences == null) {
      this.additionalReferences = new ArrayList<BOLRequestReferenceNumbersAdditionalReferences>();
    }
    this.additionalReferences.add(additionalReferencesItem);
    return this;
  }

   /**
   * Get additionalReferences
   * @return additionalReferences
  **/
  @Schema(description = "")
  public List<BOLRequestReferenceNumbersAdditionalReferences> getAdditionalReferences() {
    return additionalReferences;
  }

  public void setAdditionalReferences(List<BOLRequestReferenceNumbersAdditionalReferences> additionalReferences) {
    this.additionalReferences = additionalReferences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestReferenceNumbers boLRequestReferenceNumbers = (BOLRequestReferenceNumbers) o;
    return Objects.equals(this.pro, boLRequestReferenceNumbers.pro) &&
        Objects.equals(this.estimate, boLRequestReferenceNumbers.estimate) &&
        Objects.equals(this.shipmentId, boLRequestReferenceNumbers.shipmentId) &&
        Objects.equals(this.masterBol, boLRequestReferenceNumbers.masterBol) &&
        Objects.equals(this.bol, boLRequestReferenceNumbers.bol) &&
        Objects.equals(this.po, boLRequestReferenceNumbers.po) &&
        Objects.equals(this.additionalReferences, boLRequestReferenceNumbers.additionalReferences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pro, estimate, shipmentId, masterBol, bol, po, additionalReferences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestReferenceNumbers {\n");
    
    sb.append("    pro: ").append(toIndentedString(pro)).append("\n");
    sb.append("    estimate: ").append(toIndentedString(estimate)).append("\n");
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    masterBol: ").append(toIndentedString(masterBol)).append("\n");
    sb.append("    bol: ").append(toIndentedString(bol)).append("\n");
    sb.append("    po: ").append(toIndentedString(po)).append("\n");
    sb.append("    additionalReferences: ").append(toIndentedString(additionalReferences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
