/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Required when accessorial code INS is present in the accessorial.codes list.  
 */
@Schema(description = "Required when accessorial code INS is present in the accessorial.codes list.  ")
public class BOLRequestAccessorialsExcessLiabilityDetails {
  @SerializedName("monetaryValue")
  private String monetaryValue = null;

  @SerializedName("excessDeclaredValue")
  private String excessDeclaredValue = null;

  public BOLRequestAccessorialsExcessLiabilityDetails monetaryValue(String monetaryValue) {
    this.monetaryValue = monetaryValue;
    return this;
  }

   /**
   * Value of the cargo.   Valid Formats: * ##.## (2 decimal places only) 
   * @return monetaryValue
  **/
  @Schema(example = "100.00", description = "Value of the cargo.   Valid Formats: * ##.## (2 decimal places only) ")
  public String getMonetaryValue() {
    return monetaryValue;
  }

  public void setMonetaryValue(String monetaryValue) {
    this.monetaryValue = monetaryValue;
  }

  public BOLRequestAccessorialsExcessLiabilityDetails excessDeclaredValue(String excessDeclaredValue) {
    this.excessDeclaredValue = excessDeclaredValue;
    return this;
  }

   /**
   * Excess of declared value purchased for cargo.   Valid Formats: * ##.## (2 decimal places only) 
   * @return excessDeclaredValue
  **/
  @Schema(example = "500.00", description = "Excess of declared value purchased for cargo.   Valid Formats: * ##.## (2 decimal places only) ")
  public String getExcessDeclaredValue() {
    return excessDeclaredValue;
  }

  public void setExcessDeclaredValue(String excessDeclaredValue) {
    this.excessDeclaredValue = excessDeclaredValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsExcessLiabilityDetails boLRequestAccessorialsExcessLiabilityDetails = (BOLRequestAccessorialsExcessLiabilityDetails) o;
    return Objects.equals(this.monetaryValue, boLRequestAccessorialsExcessLiabilityDetails.monetaryValue) &&
        Objects.equals(this.excessDeclaredValue, boLRequestAccessorialsExcessLiabilityDetails.excessDeclaredValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monetaryValue, excessDeclaredValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsExcessLiabilityDetails {\n");
    
    sb.append("    monetaryValue: ").append(toIndentedString(monetaryValue)).append("\n");
    sb.append("    excessDeclaredValue: ").append(toIndentedString(excessDeclaredValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
