/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestCommoditiesHandlingUnits
 */


public class BOLRequestCommoditiesHandlingUnits {
  @SerializedName("id")
  private String id = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("tareWeight")
  private Integer tareWeight = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("stackable")
  private Boolean stackable = null;

  public BOLRequestCommoditiesHandlingUnits id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the user to associate the handling unit with one or more line items.
   * @return id
  **/
  @Schema(example = "unit1", description = "Unique identifier for the user to associate the handling unit with one or more line items.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BOLRequestCommoditiesHandlingUnits count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of handling units being described
   * @return count
  **/
  @Schema(example = "2", required = true, description = "Number of handling units being described")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public BOLRequestCommoditiesHandlingUnits type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the handling units being described  Valid Values: See the Handling_Unit_Types schema at the bottom of this page 
   * @return type
  **/
  @Schema(example = "SKD", required = true, description = "Type of the handling units being described  Valid Values: See the Handling_Unit_Types schema at the bottom of this page ")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BOLRequestCommoditiesHandlingUnits tareWeight(Integer tareWeight) {
    this.tareWeight = tareWeight;
    return this;
  }

   /**
   * Weight (in pounds) of the skids/pallets/slips used in the shipment.
   * @return tareWeight
  **/
  @Schema(example = "5", description = "Weight (in pounds) of the skids/pallets/slips used in the shipment.")
  public Integer getTareWeight() {
    return tareWeight;
  }

  public void setTareWeight(Integer tareWeight) {
    this.tareWeight = tareWeight;
  }

  public BOLRequestCommoditiesHandlingUnits weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Total weight (in pounds) for the specified handling units
   * @return weight
  **/
  @Schema(example = "1500", required = true, description = "Total weight (in pounds) for the specified handling units")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public BOLRequestCommoditiesHandlingUnits length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * The length of the handling units being described (in inches).
   * @return length
  **/
  @Schema(example = "48", required = true, description = "The length of the handling units being described (in inches).")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public BOLRequestCommoditiesHandlingUnits width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * The width of the handling units being described (in inches).
   * @return width
  **/
  @Schema(example = "48", required = true, description = "The width of the handling units being described (in inches).")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public BOLRequestCommoditiesHandlingUnits height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The height of the handling units being described (in inches).
   * @return height
  **/
  @Schema(example = "48", required = true, description = "The height of the handling units being described (in inches).")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public BOLRequestCommoditiesHandlingUnits stackable(Boolean stackable) {
    this.stackable = stackable;
    return this;
  }

   /**
   * Identifies whether or not the freight being described can be stacked on one another.  Default is false. 
   * @return stackable
  **/
  @Schema(example = "false", description = "Identifies whether or not the freight being described can be stacked on one another.  Default is false. ")
  public Boolean isStackable() {
    return stackable;
  }

  public void setStackable(Boolean stackable) {
    this.stackable = stackable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestCommoditiesHandlingUnits boLRequestCommoditiesHandlingUnits = (BOLRequestCommoditiesHandlingUnits) o;
    return Objects.equals(this.id, boLRequestCommoditiesHandlingUnits.id) &&
        Objects.equals(this.count, boLRequestCommoditiesHandlingUnits.count) &&
        Objects.equals(this.type, boLRequestCommoditiesHandlingUnits.type) &&
        Objects.equals(this.tareWeight, boLRequestCommoditiesHandlingUnits.tareWeight) &&
        Objects.equals(this.weight, boLRequestCommoditiesHandlingUnits.weight) &&
        Objects.equals(this.length, boLRequestCommoditiesHandlingUnits.length) &&
        Objects.equals(this.width, boLRequestCommoditiesHandlingUnits.width) &&
        Objects.equals(this.height, boLRequestCommoditiesHandlingUnits.height) &&
        Objects.equals(this.stackable, boLRequestCommoditiesHandlingUnits.stackable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, count, type, tareWeight, weight, length, width, height, stackable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestCommoditiesHandlingUnits {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tareWeight: ").append(toIndentedString(tareWeight)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    stackable: ").append(toIndentedString(stackable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
