/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestCommoditiesHazardousDetails
 */


public class BOLRequestCommoditiesHazardousDetails {
  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("class")
  private String propertyClass = null;

  @SerializedName("unnaNumber")
  private String unnaNumber = null;

  @SerializedName("propername")
  private String propername = null;

  @SerializedName("technicalName")
  private String technicalName = null;

  @SerializedName("packingGroup")
  private String packingGroup = null;

  @SerializedName("contractNumber")
  private String contractNumber = null;

  public BOLRequestCommoditiesHazardousDetails weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Total weight of hazardous material coveraged by one description.
   * @return weight
  **/
  @Schema(example = "45", description = "Total weight of hazardous material coveraged by one description.")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public BOLRequestCommoditiesHazardousDetails propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Class that the hazardous material is catogorized by.
   * @return propertyClass
  **/
  @Schema(example = "3", description = "Class that the hazardous material is catogorized by.")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public BOLRequestCommoditiesHazardousDetails unnaNumber(String unnaNumber) {
    this.unnaNumber = unnaNumber;
    return this;
  }

   /**
   * Proper Identification Number (UN or NA) corresponding to the Proper Shipping Name
   * @return unnaNumber
  **/
  @Schema(example = "1005", description = "Proper Identification Number (UN or NA) corresponding to the Proper Shipping Name")
  public String getUnnaNumber() {
    return unnaNumber;
  }

  public void setUnnaNumber(String unnaNumber) {
    this.unnaNumber = unnaNumber;
  }

  public BOLRequestCommoditiesHazardousDetails propername(String propername) {
    this.propername = propername;
    return this;
  }

   /**
   * Proper shipping name for the hazardous material.  From DOT regulations 172.101 
   * @return propername
  **/
  @Schema(example = "Anhydrous ammonia", description = "Proper shipping name for the hazardous material.  From DOT regulations 172.101 ")
  public String getPropername() {
    return propername;
  }

  public void setPropername(String propername) {
    this.propername = propername;
  }

  public BOLRequestCommoditiesHazardousDetails technicalName(String technicalName) {
    this.technicalName = technicalName;
    return this;
  }

   /**
   * Technical name for the hazardous material. Not all hazardous items will have a technical name.  From DOT regulations 172.101 
   * @return technicalName
  **/
  @Schema(example = "NH3", description = "Technical name for the hazardous material. Not all hazardous items will have a technical name.  From DOT regulations 172.101 ")
  public String getTechnicalName() {
    return technicalName;
  }

  public void setTechnicalName(String technicalName) {
    this.technicalName = technicalName;
  }

  public BOLRequestCommoditiesHazardousDetails packingGroup(String packingGroup) {
    this.packingGroup = packingGroup;
    return this;
  }

   /**
   * Hazmat Packing Group number. Not all hazmat items have a packing group
   * @return packingGroup
  **/
  @Schema(example = "2", description = "Hazmat Packing Group number. Not all hazmat items have a packing group")
  public String getPackingGroup() {
    return packingGroup;
  }

  public void setPackingGroup(String packingGroup) {
    this.packingGroup = packingGroup;
  }

  public BOLRequestCommoditiesHazardousDetails contractNumber(String contractNumber) {
    this.contractNumber = contractNumber;
    return this;
  }

   /**
   * The contract number with the hazardous materials contact
   * @return contractNumber
  **/
  @Schema(example = "54321", description = "The contract number with the hazardous materials contact")
  public String getContractNumber() {
    return contractNumber;
  }

  public void setContractNumber(String contractNumber) {
    this.contractNumber = contractNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestCommoditiesHazardousDetails boLRequestCommoditiesHazardousDetails = (BOLRequestCommoditiesHazardousDetails) o;
    return Objects.equals(this.weight, boLRequestCommoditiesHazardousDetails.weight) &&
        Objects.equals(this.propertyClass, boLRequestCommoditiesHazardousDetails.propertyClass) &&
        Objects.equals(this.unnaNumber, boLRequestCommoditiesHazardousDetails.unnaNumber) &&
        Objects.equals(this.propername, boLRequestCommoditiesHazardousDetails.propername) &&
        Objects.equals(this.technicalName, boLRequestCommoditiesHazardousDetails.technicalName) &&
        Objects.equals(this.packingGroup, boLRequestCommoditiesHazardousDetails.packingGroup) &&
        Objects.equals(this.contractNumber, boLRequestCommoditiesHazardousDetails.contractNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weight, propertyClass, unnaNumber, propername, technicalName, packingGroup, contractNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestCommoditiesHazardousDetails {\n");
    
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    unnaNumber: ").append(toIndentedString(unnaNumber)).append("\n");
    sb.append("    propername: ").append(toIndentedString(propername)).append("\n");
    sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
    sb.append("    packingGroup: ").append(toIndentedString(packingGroup)).append("\n");
    sb.append("    contractNumber: ").append(toIndentedString(contractNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
