/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLRequestAccessorialsHazardousDetailsEmergencyContact
 */


public class BOLRequestAccessorialsHazardousDetailsEmergencyContact {
  @SerializedName("name")
  private String name = null;

  @SerializedName("phone")
  private String phone = null;

  public BOLRequestAccessorialsHazardousDetailsEmergencyContact name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name of who should be contacted in the case of a hazardous materials-related issue.
   * @return name
  **/
  @Schema(example = "Manny Delgato", description = "Full name of who should be contacted in the case of a hazardous materials-related issue.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BOLRequestAccessorialsHazardousDetailsEmergencyContact phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Phone number of who should be contacted in the case of a hazardous materials-related issue.  Valid Formats: * ########## (10 digits - Area code + phone) 
   * @return phone
  **/
  @Schema(example = "7775558899", description = "Phone number of who should be contacted in the case of a hazardous materials-related issue.  Valid Formats: * ########## (10 digits - Area code + phone) ")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsHazardousDetailsEmergencyContact boLRequestAccessorialsHazardousDetailsEmergencyContact = (BOLRequestAccessorialsHazardousDetailsEmergencyContact) o;
    return Objects.equals(this.name, boLRequestAccessorialsHazardousDetailsEmergencyContact.name) &&
        Objects.equals(this.phone, boLRequestAccessorialsHazardousDetailsEmergencyContact.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, phone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsHazardousDetailsEmergencyContact {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
