/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLResponseImages;
import com.nmfta.ebol.model.BOLResponseMessageStatus;
import com.nmfta.ebol.model.BOLResponseReferenceNumbers;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BOLResponse
 */


public class BOLResponse {
  @SerializedName("referenceNumbers")
  private BOLResponseReferenceNumbers referenceNumbers = null;

  @SerializedName("images")
  private BOLResponseImages images = null;

  @SerializedName("messageStatus")
  private BOLResponseMessageStatus messageStatus = null;

  public BOLResponse referenceNumbers(BOLResponseReferenceNumbers referenceNumbers) {
    this.referenceNumbers = referenceNumbers;
    return this;
  }

   /**
   * Get referenceNumbers
   * @return referenceNumbers
  **/
  @Schema(description = "")
  public BOLResponseReferenceNumbers getReferenceNumbers() {
    return referenceNumbers;
  }

  public void setReferenceNumbers(BOLResponseReferenceNumbers referenceNumbers) {
    this.referenceNumbers = referenceNumbers;
  }

  public BOLResponse images(BOLResponseImages images) {
    this.images = images;
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public BOLResponseImages getImages() {
    return images;
  }

  public void setImages(BOLResponseImages images) {
    this.images = images;
  }

  public BOLResponse messageStatus(BOLResponseMessageStatus messageStatus) {
    this.messageStatus = messageStatus;
    return this;
  }

   /**
   * Get messageStatus
   * @return messageStatus
  **/
  @Schema(description = "")
  public BOLResponseMessageStatus getMessageStatus() {
    return messageStatus;
  }

  public void setMessageStatus(BOLResponseMessageStatus messageStatus) {
    this.messageStatus = messageStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLResponse boLResponse = (BOLResponse) o;
    return Objects.equals(this.referenceNumbers, boLResponse.referenceNumbers) &&
        Objects.equals(this.images, boLResponse.images) &&
        Objects.equals(this.messageStatus, boLResponse.messageStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceNumbers, images, messageStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLResponse {\n");
    
    sb.append("    referenceNumbers: ").append(toIndentedString(referenceNumbers)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    messageStatus: ").append(toIndentedString(messageStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
