/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nmfta.ebol.model.BOLRequestAccessorialsHazardousDetailsEmergencyContact;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Required if accessorial codes list contains HAZ and/or if any commodity line item&#x27;s hazardous flag is set to true. 
 */
@Schema(description = "Required if accessorial codes list contains HAZ and/or if any commodity line item's hazardous flag is set to true. ")

public class BOLRequestAccessorialsHazardousDetails {
  @SerializedName("emergencyContact")
  private BOLRequestAccessorialsHazardousDetailsEmergencyContact emergencyContact = null;

  public BOLRequestAccessorialsHazardousDetails emergencyContact(BOLRequestAccessorialsHazardousDetailsEmergencyContact emergencyContact) {
    this.emergencyContact = emergencyContact;
    return this;
  }

   /**
   * Get emergencyContact
   * @return emergencyContact
  **/
  @Schema(description = "")
  public BOLRequestAccessorialsHazardousDetailsEmergencyContact getEmergencyContact() {
    return emergencyContact;
  }

  public void setEmergencyContact(BOLRequestAccessorialsHazardousDetailsEmergencyContact emergencyContact) {
    this.emergencyContact = emergencyContact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BOLRequestAccessorialsHazardousDetails boLRequestAccessorialsHazardousDetails = (BOLRequestAccessorialsHazardousDetails) o;
    return Objects.equals(this.emergencyContact, boLRequestAccessorialsHazardousDetails.emergencyContact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emergencyContact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BOLRequestAccessorialsHazardousDetails {\n");
    
    sb.append("    emergencyContact: ").append(toIndentedString(emergencyContact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
