/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Valid values: * BAG - Bag * BAL - Bale * BBL - Barrel * BSK - Basket * BIN - Bin * BOX - Box * BXT - Bucket * BCH - Bunch * BDL - Bundle * CAB - Cabinet * CAG - Cage * CAN - Can * CBY - Carboy * CAR - Carrier * CTN - Carton * CAS - Case * CSK - Cask * CHS - Chest * COL - Coil * CNT - Container * COR - Cores * CRT - Crate * CYL - Cylinder * DRM - Drum * DBK - Dry Bulk * ENV - Envelope * FIR - Firkin * GLD - Gaylord * HPR - Hamper * HGH - Hogshead * HRB - On Hanger or Rack in Boxes * INT - Intermediate Bulk Container * JAR - Jar * JCN - Jerrycan * KEG - Keg * KIT - Kit * LIF - Lifts * LBK - Liquid Bulk * LSE - Loose * MXD - Mixed * OTH - Other * PKG - Package * PCK - Packed * PAL - Pail * PAT - Pallet * PCS - Piece * PLN - Pipe Line * RCK - Rack * REL - Reel * ROL - Roll * SKD - Skid * SLP - Slip Sheet * SPL - Spool * TNK - Tank * TBN - Tote * TRY - Tray * TRU - Truckload * TRK - Trunk * TUB - Tub * TBE - Tube * UNT - Unit * VPK - Van Pack * WRP - Wrapped 
 */
@Schema(description = "Valid values: * BAG - Bag * BAL - Bale * BBL - Barrel * BSK - Basket * BIN - Bin * BOX - Box * BXT - Bucket * BCH - Bunch * BDL - Bundle * CAB - Cabinet * CAG - Cage * CAN - Can * CBY - Carboy * CAR - Carrier * CTN - Carton * CAS - Case * CSK - Cask * CHS - Chest * COL - Coil * CNT - Container * COR - Cores * CRT - Crate * CYL - Cylinder * DRM - Drum * DBK - Dry Bulk * ENV - Envelope * FIR - Firkin * GLD - Gaylord * HPR - Hamper * HGH - Hogshead * HRB - On Hanger or Rack in Boxes * INT - Intermediate Bulk Container * JAR - Jar * JCN - Jerrycan * KEG - Keg * KIT - Kit * LIF - Lifts * LBK - Liquid Bulk * LSE - Loose * MXD - Mixed * OTH - Other * PKG - Package * PCK - Packed * PAL - Pail * PAT - Pallet * PCS - Piece * PLN - Pipe Line * RCK - Rack * REL - Reel * ROL - Roll * SKD - Skid * SLP - Slip Sheet * SPL - Spool * TNK - Tank * TBN - Tote * TRY - Tray * TRU - Truckload * TRK - Trunk * TUB - Tub * TBE - Tube * UNT - Unit * VPK - Van Pack * WRP - Wrapped ")

public class HandlingUnitTypes {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandlingUnitTypes {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
