/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Valid Values: * Airport - Airport * Church - Church * Club - Country Club, Social Club * Construction - Construction Site * Fair - Fair, Carnival, Flea Market * Farm - Farm, Ranch, Vinyard, Orchard * Hotel - Hotel, Motel, Inn, Resteraunt * Mine - Mine, Mill * Other - Other * Park - Amusement Park, Camp, Marina * Port - Port * School - School, University, Library * Secure - Military, Prison, Power Plant, Utility * Storage - Self Storage Unit * Tradeshow -Tradeshow, Exhibition, Expo 
 */
@Schema(description = "Valid Values: * Airport - Airport * Church - Church * Club - Country Club, Social Club * Construction - Construction Site * Fair - Fair, Carnival, Flea Market * Farm - Farm, Ranch, Vinyard, Orchard * Hotel - Hotel, Motel, Inn, Resteraunt * Mine - Mine, Mill * Other - Other * Park - Amusement Park, Camp, Marina * Port - Port * School - School, University, Library * Secure - Military, Prison, Power Plant, Utility * Storage - Self Storage Unit * Tradeshow -Tradeshow, Exhibition, Expo ")

public class LimitedAccessTypes {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LimitedAccessTypes {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
