/*
 * Electronic Bill Of Lading Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nmfta.ebol.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Valid values: * AL - Alabama * AK - Alaska * AZ - Arizona * AR - Arkansas * CA - California * CO - Colorado * CT - Connecticut * DC - District of Columbia * DE - Delaware * FL - Florida * GA - Georgia * HI - Hawaii * ID - Idaho * IL - Illinois * IN - Indiana * IA - Iowa * KS - Kansas * KY - Kentucky * LA - Louisiana * ME - Maine * MD - Maryland * MA - Massachusetts * MI - Michigan * MN - Minnesota * MS - Mississippi * MO - Missouri * MT - Montana * NE - Nebraska * NV - Nevada * NH - New Hampshire * NJ - New Jersey * NM - New Mexico * NY - New York * NC - North Carolina * ND - North Dakota * OH - Ohio * OK - Oklahoma * OR - Oregon * PA - Pennsylvania * RI - Rhode Island * SC - South Carolina * SD - South Dakota * TN - Tennessee * TX - Texas * UT - Utah * VT - Vermont * VA - Virginia * WA - Washington * WV - West Virginia * WI - Wisconsin * WY - Wyoming * AB - Alberta * BC - British Columbia * MB - Manitoba * NB - New Brunswick * NL - Newfoundland and Labrador * NS - Nova Scotia * NT - Northwest Territories * NU - Nunavut * ON - Ontario * PE - Prince Edward Island * QC - Quebec * SK - Saskatchewan * YT - Yukon 
 */
@Schema(description = "Valid values: * AL - Alabama * AK - Alaska * AZ - Arizona * AR - Arkansas * CA - California * CO - Colorado * CT - Connecticut * DC - District of Columbia * DE - Delaware * FL - Florida * GA - Georgia * HI - Hawaii * ID - Idaho * IL - Illinois * IN - Indiana * IA - Iowa * KS - Kansas * KY - Kentucky * LA - Louisiana * ME - Maine * MD - Maryland * MA - Massachusetts * MI - Michigan * MN - Minnesota * MS - Mississippi * MO - Missouri * MT - Montana * NE - Nebraska * NV - Nevada * NH - New Hampshire * NJ - New Jersey * NM - New Mexico * NY - New York * NC - North Carolina * ND - North Dakota * OH - Ohio * OK - Oklahoma * OR - Oregon * PA - Pennsylvania * RI - Rhode Island * SC - South Carolina * SD - South Dakota * TN - Tennessee * TX - Texas * UT - Utah * VT - Vermont * VA - Virginia * WA - Washington * WV - West Virginia * WI - Wisconsin * WY - Wyoming * AB - Alberta * BC - British Columbia * MB - Manitoba * NB - New Brunswick * NL - Newfoundland and Labrador * NS - Nova Scotia * NT - Northwest Territories * NU - Nunavut * ON - Ontario * PE - Prince Edward Island * QC - Quebec * SK - Saskatchewan * YT - Yukon ")

public class StateProvinceCodes {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StateProvinceCodes {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
